/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tree;

/**
 *
 * @author PST91
 */
// ======= DO NOT EDIT THIS FILE ============
public class Node<T>
  {T info;
   Node left,right;
   int bal,level;
   Node(T x)
     {info=x;left=right=null;
     }  

    Node() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   }
